In [1]:
from __future__ import division
from __future__ import print_function

# Allowed libraries 
import numpy as np
import pandas as pd
import scipy as sp
import scipy.special
import heapq as pq
import matplotlib as mp
import matplotlib.pyplot as plt
import math
from itertools import product, combinations
from collections import OrderedDict as odict
import collections
from graphviz import Digraph, Graph
from tabulate import tabulate
import copy
import sys
import os
import datetime
import sklearn
import ast
import re

In [11]:
tran_matrix_0 = pd.read_csv("tran_matrix0.csv")
tran_matrix_1 = pd.read_csv("tran_matrix1.csv")
tran_matrix_2 = pd.read_csv("tran_matrix2.csv")
tran_matrix_3 = pd.read_csv("tran_matrix3.csv")
tran_matrix_4 = pd.read_csv("tran_matrix4.csv")

In [24]:
tran_matrix0 = np.array([tran_matrix_0.iloc[i].values.tolist()[2:] for i in range(tran_matrix_0.shape[0])])
tran_matrix1 = np.array([tran_matrix_1.iloc[i].values.tolist()[2:] for i in range(tran_matrix_1.shape[0])])
tran_matrix2 = np.array([tran_matrix_2.iloc[i].values.tolist()[2:] for i in range(tran_matrix_2.shape[0])])
tran_matrix3 = np.array([tran_matrix_3.iloc[i].values.tolist()[2:] for i in range(tran_matrix_3.shape[0])])
tran_matrix4 = np.array([tran_matrix_4.iloc[i].values.tolist()[2:] for i in range(tran_matrix_4.shape[0])])

In [27]:
init = np.array([0]*40 + [23])

In [30]:
np.dot(init,tran_matrix0)

array([ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  5.75  ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
        6.67  ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.    , 10.7824])

### Use Different Transition Matrix for Different Times

In [36]:
current_time = datetime.time(hour=8,minute=0)

In [33]:
time_step = datetime.timedelta(minutes=2)
time_step

datetime.timedelta(seconds=120)

In [41]:
(datetime.datetime.combine(datetime.date.today(), current_time)).time() >= current_time

True

In [42]:
def choose_tran_matrix(time):
    if(time<datetime.time(hour=8,minute=1)):
        return tran_matrix0 
    elif (time<datetime.time(hour=8,minute=5)):
        return tran_matrix1 
    elif (time<datetime.time(hour=17,minute=30)):
        return tran_matrix2
    elif (time<datetime.time(hour=17,minute=41)):
        return tran_matrix3 
    else:
        return tran_matrix4 

In [46]:
current_time = datetime.time(hour=8,minute=1,second=0)

In [47]:
choose_tran_matrix(current_time)

array([[1.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.9   , ..., 0.    , 0.    , 0.    ],
       ...,
       [0.    , 0.    , 0.    , ..., 0.6944, 0.11  , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.13  , 0.6923, 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ]])

In [48]:
tran_matrix1

array([[1.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.9   , ..., 0.    , 0.    , 0.    ],
       ...,
       [0.    , 0.    , 0.    , ..., 0.6944, 0.11  , 0.    ],
       [0.    , 0.    , 0.    , ..., 0.13  , 0.6923, 0.    ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.    , 0.    ]])

In [58]:
people = round(np.random.normal(20,1))
people

21